version: '3.3'

services:
  app-server-collector:
    build:
      context: repos_collector
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/app?useSSL=false
      SPRING_DATASOURCE_USERNAME: git
      SPRING_DATASOURCE_PASSWORD: git
    networks:
      - backend

  app-server-top:
    build:
      context: top_repos
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/app?useSSL=false
      SPRING_DATASOURCE_USERNAME: git
      SPRING_DATASOURCE_PASSWORD: git
    networks:
      - backend

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: git
      MYSQL_PASSWORD: git
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: